// Mocks generated by Mockito 5.1.0 from annotations
// in veryfi_dart/test/veryfi_dart_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:veryfi_dart/model/veryfi_credentials.dart' as _i2;
import 'package:veryfi_dart/network/network_request_manager.dart' as _i5;
import 'package:veryfi_dart/veryfi_dart.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeVeryfiCredentials_0 extends _i1.Fake
    implements _i2.VeryfiCredentials {}

/// A class which mocks [VeryfiDart].
///
/// See the documentation for Mockito's code generation for more information.
class MockVeryfiDart extends _i1.Mock implements _i3.VeryfiDart {
  MockVeryfiDart() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VeryfiCredentials get credentials =>
      (super.noSuchMethod(Invocation.getter(#credentials),
          returnValue: _FakeVeryfiCredentials_0()) as _i2.VeryfiCredentials);
  @override
  String get apiVersion =>
      (super.noSuchMethod(Invocation.getter(#apiVersion), returnValue: '')
          as String);
  @override
  String get baseUrl =>
      (super.noSuchMethod(Invocation.getter(#baseUrl), returnValue: '')
          as String);
  @override
  _i4.Future<Map<String, dynamic>> getDocuments() => (super.noSuchMethod(
          Invocation.method(#getDocuments, []),
          returnValue: Future<Map<String, dynamic>>.value(<String, dynamic>{}))
      as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<Map<String, dynamic>> getDocumentById(String? documentId) =>
      (super.noSuchMethod(Invocation.method(#getDocumentById, [documentId]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<Map<String, dynamic>> deleteDocument(String? documentId) =>
      (super.noSuchMethod(Invocation.method(#deleteDocument, [documentId]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<Map<String, dynamic>> updateDocument(
          String? documentId, Map<String, dynamic>? params) =>
      (super.noSuchMethod(
              Invocation.method(#updateDocument, [documentId, params]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<Map<String, dynamic>> processDocumentFromURL(
          {String? fileUrl,
          List<String>? fileUrls,
          List<String>? categories,
          bool? deleteAfterProcessing = false,
          int? boostMode = 0,
          String? externalId,
          int? maxPagesToProcess = 1}) =>
      (super.noSuchMethod(
              Invocation.method(#processDocumentFromURL, [], {
                #fileUrl: fileUrl,
                #fileUrls: fileUrls,
                #categories: categories,
                #deleteAfterProcessing: deleteAfterProcessing,
                #boostMode: boostMode,
                #externalId: externalId,
                #maxPagesToProcess: maxPagesToProcess
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<Map<String, dynamic>> processDocument(
          String? fileName, String? fileData,
          {List<String>? categories,
          bool? deleteAfterProcessing = false,
          Map<String, dynamic>? params}) =>
      (super.noSuchMethod(
              Invocation.method(#processDocument, [
                fileName,
                fileData
              ], {
                #categories: categories,
                #deleteAfterProcessing: deleteAfterProcessing,
                #params: params
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i4.Future<Map<String, dynamic>>);
  @override
  _i4.Future<Map<String, dynamic>> request(
          _i5.HTTPMethod? method, _i5.APIPath? path,
          {Map<String, dynamic>? queryItems,
          Map<String, dynamic>? body,
          String? queryItem}) =>
      (super.noSuchMethod(
              Invocation.method(#request, [
                method,
                path
              ], {
                #queryItems: queryItems,
                #body: body,
                #queryItem: queryItem
              }),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i4.Future<Map<String, dynamic>>);
  @override
  Map<String, dynamic> processResponse(_i6.Response? response) =>
      (super.noSuchMethod(Invocation.method(#processResponse, [response]),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  String pathEnumToUrl(_i5.APIPath? path) =>
      (super.noSuchMethod(Invocation.method(#pathEnumToUrl, [path]),
          returnValue: '') as String);
  @override
  Map<String, String> getHeaders(Map<String, dynamic>? params) =>
      (super.noSuchMethod(Invocation.method(#getHeaders, [params]),
          returnValue: <String, String>{}) as Map<String, String>);
  @override
  String generateSignature(Map<String, dynamic>? params, String? timestamp) =>
      (super.noSuchMethod(
          Invocation.method(#generateSignature, [params, timestamp]),
          returnValue: '') as String);
}
