name: veryfi_dart
description: Dart module for communicating with the Veryfi OCR API.
version: 0.0.1
homepage: https://www.veryfi.com

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  http: ^0.13.4
  crypto: ^3.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.8
  mockito: ^5.1.0
