name: Main

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Run tests
        run: flutter test --coverage

      - name: check code coverage
        run: |
          cd .github/metrics/
          python generate_badge.py
          cd ../../
          
      - name: Commit Code Coverage Image to Repo
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Github actions
          author_email: veryfi@veryfi.com
          message: "Update report"
          add: "./.github/metrics"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
