name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      
      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage
        
      - name: Yarn lcov2badge
        run: |
          npm install yarn -g
          yarn
          yarn add lcov2badge
            
      - name: Generate coverage badge
        run: | 
          cd .github/metrics/
          node coverage.js
